name: Update Naukri Profile

on:
  schedule:
    - cron: '30 3 * * *'  # 9:00 AM IST
    - cron: '30 4 * * *'  # 10:00 AM IST
  workflow_dispatch:      # allows manual trigger

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # ✅ use valid modern version

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Install Chrome & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          wget -O chromedriver.zip "https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip"
          unzip chromedriver.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Profile Update Script
        run: python update_profile.py
